name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # roda todo dia
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: maxforcedev
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.svg?palette=github-dark

      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
